#define UDP_PORT 22145
#define CLIENT_SERVICE_MESSAGE "LIGHT PET CLIENT SERVICE ADVERTISEMENT MESSAGE"
#define SERVER_SERVICE_MESSAGE "LIGHT PET SERVER SERVICE ADVERTISEMENT MESSAGE"
#define MICROPHONE_SAMPLE_RATE 20000
#define LIGHT_SAMPLE_RATE 20000
#define TEMP_HUMIDITY_SAMPLE_RATE 1
#define DATA_BUFFER_SIZE 3
#define DATA_SEND_RATE 50
#define DATA_RECEIVE_RATE 50
#define OUTPUT_BUFFER_SIZE 8092
#define ADVERTISEMENT_RATE 10
#define UDP_MAX_SIZE 65507
#define NTP_SYNC_TIMEOUT 3600
